name: Update badges
on:
  workflow_dispatch:
  schedule:
    # Runs daily at 23:25 UTC
    - cron: "25 23 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: miguel-horta
